### ISSUE TITLE
Init router

### ISSUE THREAD

**Issue by nambn-code** [btcs-nambn/appoiment-app#2]
Tạo các đường dẫn cần thiết cho app
- thêm router
- thêm tailwind

**Comment by nguyendanglinh270792** [comment]
Trang Pages chính bên user là UserInfor(lưu thông tin khách hàng) và MakeAnAppointment(nơi khách hàng đặt lịch thêm sửa xoá và theo dõi lịch hẹn của cty) 
Khi người dùng truy cập vào  app họ sẽ phải đăng nhập đăng nhập thành công sẽ được chuyển qua trang UserInfor  trong trang UserInfor sẽ có thông tin của khách hàng  và 1 link đi đến trang MakeAnAppointment
